<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSYlQuMc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSYlQuMc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSYlQuMc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSYlQuMc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSYlQuMc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SYlQuMc',
    'container.build_id' => '97deebba',
    'container.build_time' => 1591892613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSYlQuMc');
