<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\PagesController::home'], [], [['text', '/']], [], []],
    'app_about' => [[], ['_controller' => 'App\\Controller\\PagesController::about'], [], [['text', '/about']], [], []],
];
